# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Project 47 - TagViewApp' do

use_frameworks!

pod 'PageMenu'

end

target 'Project 47 - TagViewAppTests' do

end

target 'Project 47 - TagViewAppUITests' do

end

